on:
  push:
    branches:
      - master
name: Build and Deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@master
      # Step 2
      - name: Install and Build
        run: |          
          #npm install
          #node node_modules/@angular/cli/bin/ng build --prod          
      # Step 3    
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          touch index.html
          echo 'hola mundo' >> index.html
          git status          
          git checkout gh-pages
          git add .
          git commit -m "Add changes"
          git push origin gh-pages